### ISSUE TITLE
Etag tween geeft soms errors

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/crabpy_pyramid#102]
```
  File ".venv/lib/python3.6/site-packages/crabpy_pyramid/__init__.py", line 194, in conditional_http_tween
    if request.matched_route.name in GENERATE_ETAG_ROUTE_NAMES:
AttributeError: 'NoneType' object has no attribute 'name'
```
Bij requests naar onbestaande URLs bij een applicatie is de `matched_route` None. 
In dit geval is er voor de tween niks te doen. Momenteel crasht de tween hierop.

Todo: if-check op None --> `return response` if none.

**Comment by cedrikv** [comment]
mogelijk gerelateerd: sinds versie 0.8 zijn er ook tween errorrs bij het ophalen van de favico (http://local.onroerenderfgoed.be:6543/favicon.ico):
```
Serving on http://0.0.0.0:6543
2019-04-25 15:53:38,852 ERROR [proces_notas.views.exceptions][waitress] 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/vandercf/.virtualenvs/proces_notas/local/lib/python2.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/vandercf/.virtualenvs/proces_notas/local/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/vandercf/.virtualenvs/proces_notas/local/lib/python2.7/site-packages/crabpy_pyramid/__init__.py", line 194, in conditional_http_tween
    if request.matched_route.name in GENERATE_ETAG_ROUTE_NAMES:
AttributeError: 'NoneType' object has no attribute 'name'
2019-04-25 15:53:39,234 ERROR [proces_notas.views.exceptions][waitress] 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/vandercf/.virtualenvs/proces_notas/local/lib/python2.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/vandercf/.virtualenvs/proces_notas/local/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/vandercf/.virtualenvs/proces_notas/local/lib/python2.7/site-packages/crabpy_pyramid/__init__.py", line 194, in conditional_http_tween
    if request.matched_route.name in GENERATE_ETAG_ROUTE_NAMES:
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by claeyswo** [comment]
Zelfde probleem

**Comment by cedrikv** [comment]
Deze heb ik nu ook bij geoportaal, ik krijg een error en soms stoppen de kaartlagen zelgs met laden daarna :/

![image](https://user-images.githubusercontent.com/1849458/57445863-8de5a400-7253-11e9-867b-282378d8e24b.png)
